[package]
name = "resources"
version = "0.1.0"
authors = ["ManicRobot <manicrobot@protonmail.com>"]
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.1"
pci-ids = "0.2.5"
glob = "0.3.0"
lazy_static = "1.4.0"
anyhow = "1.0.66"
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.16.0"
gtk = { version = "0.6.0", features = ["v4_8"], package = "gtk4" }
adw = { version = "0.3.0", features = ["v1_2"], package = "libadwaita" }
nparse = "0.0.4"
regex = "1.7.0"
serde_json = "1.0"
sysconf = "0.3.4"
zbus = "3.5.0"
nvml-wrapper = "0.8.0"
zvariant = "3.8"
futures-util = "0.3.25"
unescape = "0.1.0"
nix = { version = "0.26.1", features = ["signal"] }
users = "0.11.0"
plotters = { version = "0.3.4", default_features = false, features = ["area_series"] }
plotters-cairo = { path = "lib/plotters-cairo" }
