[package]
name = "resources"
version = "1.2.1"
authors = ["nokyan <nokyan@tuta.io>"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
process-data = { path = "lib/process_data" }
glob = "0.3.1"
anyhow = "1.0.71"
log = "0.4.19"
pretty_env_logger = "0.5"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7.3", features = ["v4_10"], package = "gtk4" }
adw = { version = "0.5.2", features = ["v1_4"], package = "libadwaita" }
nparse = "0.0.10"
regex = "1.8.4"
serde_json = "1.0"
sysconf = "0.3.4"
nvml-wrapper = "0.9.0"
unescape = "0.1.0"
nix = { version = "0.27.1", features = ["signal"] }
uzers = "0.11.3"
plotters = { version = "0.3.4", default_features = false, features = [
    "area_series",
] }
plotters-cairo = "0.5.0"
serde = { version = "1.0.180", features = ["serde_derive"] }
rmp-serde = "1.1.2"
rust-ini = "0.20.0"
gtk-macros = "0.3.0"
strum = "0.25.0"
strum_macros = "0.25.2"
once_cell = "1.18.0"
hashbrown = "0.14.1"
expanduser = "1.2.2"
paste = "1.0.14"
num_cpus = "1.16.0"
